name: Release

on:
  workflow_dispatch:

jobs:
  release-macos:
    name: macOS Binary Release
    runs-on: macos-latest
    env:
      CGO_ENABLED: 1
      GOOS: darwin
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install fyne for packaging
        run: go install fyne.io/fyne/v2/cmd/fyne@latest

      - name: Install depdendencies
        run: go mod tidy

      - name: Pre-build commands
        run: |
          mkdir -p ./build/dff-macos-amd64
          mkdir -p ./build/dff-macos-arm64
          cp ./License ./build/dff-macos-amd64/license
          cp ./License ./build/dff-macos-arm64/license

      - name: Build for amd64
        env:
          GOARCH: amd64
        run: go build -o ./build/dff-macos-amd64/dff-macos-amd64 ./cmd/dff.go

      - name: Build for arm64
        env:
          GOARCH: arm64
        run: go build -o ./build/dff-macos-arm64/dff-macos-arm64 ./cmd/dff.go

      - name: Create zip
        run: |
          7z a dff-macos-amd64.zip ./build/dff-macos-amd64
          7z a dff-macos-arm64.zip ./build/dff-macos-arm64

      - name: Post-build commands
        run: |
          md5 dff-macos-amd64.zip > dff-macos-amd64.zip.md5
          md5 dff-macos-arm64.zip > dff-macos-arm64.zip.md5

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            dff-macos-amd64.zip
            dff-macos-amd64.zip.md5
            dff-macos-arm64.zip
            dff-macos-arm64.zip.md5

  release-win:
    name: Windows Binary Release
    runs-on: windows-latest
    env:
      GOOS: windows
      GOARCH: amd64
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install depdendencies
        run: go mod tidy

      - name: Pre-build commands
        run: |
          mkdir .\build\dff-windows-amd64
          cp .\License .\build\dff-windows-amd64\License

      - name: Build
        run: go build -o .\build\dff-windows-amd64\dff-windows-amd64.exe -ldflags -H=windowsgui .\cmd\dff.go

      - name: Create zip
        run: 7z a dff-windows-amd64.zip .\build\dff-windows-amd64

      - name: Post-build commands
        run: certutil -hashfile dff-windows-amd64.zip | findstr /V ":" > dff-windows-amd64.zip.md5

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            dff-windows-amd64.zip
            dff-windows-amd64.zip.md5
